// Generated by apps/web/scripts/generate-changelog.mjs. Do not edit by hand.
import type { ChangelogEntry } from './changelog';

export const generatedChangelog = [
  {
    "slug": "2026-07-22",
    "title": "Faster, More Reliable Graphs and Better Product Feedback",
    "summary": "Treease improves graph rendering performance and stability, adds an in-app feedback dialog, and strengthens product discoverability.",
    "date": "2026-07-22",
    "isoDate": "2026-07-22",
    "tags": [
      "performance",
      "reliability",
      "feedback",
      "SEO"
    ],
    "author": "Treease Team",
    "featured": true,
    "sections": [
      {
        "heading": "Graph performance and reliability",
        "paragraphs": [
          "Large graph scenes now render more efficiently by focusing work on the visible viewport and avoiding unnecessary redraws.",
          "Graph ownership and streaming table layout are more stable during runtime startup and updates. Usage requests also back off more gracefully after rate limits."
        ]
      },
      {
        "heading": "A clearer product experience",
        "paragraphs": [
          "Treease now includes a generated changelog page and a BugDrop feedback dialog, making it easier to follow product updates and report problems.",
          "Repository-facing product text has been standardized in English, while discoverability improvements help more users find Treease."
        ]
      },
      {
        "heading": "Account and usage behavior",
        "paragraphs": [
          "Client and user usage metering is now unified. Anonymous sign-in has been removed, subscription webhook handling is idempotent, and anonymous usage identity is preserved consistently where supported."
        ]
      }
    ],
    "tutorialLinks": []
  },
  {
    "slug": "2026-07-19",
    "title": "Smoother Accounts, Sharing, Billing, and Editor Navigation",
    "summary": "Treease brings a more dependable account and sharing experience, clearer billing flows, improved editor navigation, and a smoother homepage demo.",
    "date": "2026-07-19",
    "isoDate": "2026-07-19",
    "tags": [
      "accounts",
      "sharing",
      "billing",
      "editor",
      "AI"
    ],
    "author": "Treease Team",
    "featured": false,
    "sections": [
      {
        "heading": "Accounts and sign-in",
        "paragraphs": [
          "OAuth linking and fallback login flows are more resilient, including recovery from OAuth link failures and clearer handling of anonymous account details.",
          "Account navigation is more consistent, with improved menu loading, icons, home navigation, and protection for anonymous sign-in."
        ]
      },
      {
        "heading": "Sharing, selection, and graph viewing",
        "paragraphs": [
          "Shared graph links now use a unified restore flow that preserves editor selections and reliably restores graph focus after the runtime is ready.",
          "Graph selection remains stable across hover interactions, and the CLI graph can be prerendered for web viewing."
        ]
      },
      {
        "heading": "Billing and product polish",
        "paragraphs": [
          "Pricing checkout now adapts to the user's sign-in state, postpaid usage is gated correctly, and anonymous users can see their usage summary.",
          "Treease adds a recursive compact operator, removes workspace commands from the command panel, improves semantic text colors, and makes homepage demo playback smoother.",
          "AI credential routing and workspace file actions are available through clearer product flows."
        ]
      }
    ],
    "tutorialLinks": [
      {
        "href": "/tutorial/json-viewer",
        "label": "JSON Viewer Online: Explore JSON as a Tree and Graph"
      }
    ]
  },
  {
    "slug": "2026-07-12",
    "title": "Faster Stream Imports and a New Desktop Workspace Foundation",
    "summary": "Streaming trace imports are faster, and Treease gains the foundation for a desktop workspace and release channel.",
    "date": "2026-07-12",
    "isoDate": "2026-07-12",
    "tags": [
      "performance",
      "desktop"
    ],
    "author": "Treease Team",
    "featured": false,
    "sections": [
      {
        "heading": "Performance",
        "paragraphs": [
          "Streamed trace imports now complete more efficiently, improving responsiveness when loading large inputs."
        ]
      },
      {
        "heading": "Desktop workspace",
        "paragraphs": [
          "Treease adds a desktop workspace host and release pipeline, establishing a dedicated desktop experience."
        ]
      }
    ],
    "tutorialLinks": []
  },
  {
    "slug": "2026-07-08",
    "title": "Clearer Structured Compare Diffs",
    "summary": "Compare results now use explicit byte spans so differences are represented more accurately and remain easier to inspect.",
    "date": "2026-07-08",
    "isoDate": "2026-07-08",
    "tags": [
      "compare",
      "JSON"
    ],
    "author": "Treease Team",
    "featured": false,
    "sections": [
      {
        "heading": "More precise comparisons",
        "paragraphs": [
          "Structured compare diffs now identify exact changed spans, improving the accuracy and clarity of comparison results."
        ]
      }
    ],
    "tutorialLinks": [
      {
        "href": "/tutorial/compare-json-structurally",
        "label": "How to Compare JSON Structurally"
      },
      {
        "href": "/tutorial/json-compare",
        "label": "JSON Compare Online: Compare JSON Structurally"
      }
    ]
  },
  {
    "slug": "2026-07-07",
    "title": "More Stable Graph Rendering During Workspace Changes",
    "summary": "Graph rendering and workspace resizing are now more dependable, with fewer readiness races and redundant controllers.",
    "date": "2026-07-07",
    "isoDate": "2026-07-07",
    "tags": [
      "reliability",
      "graph",
      "workspace"
    ],
    "author": "Treease Team",
    "featured": false,
    "sections": [
      {
        "heading": "Rendering reliability",
        "paragraphs": [
          "Workspace resizing now stays synchronized with the graph, and graph readiness is handled more consistently during startup and updates.",
          "Graph probing uses a single controller, reducing duplicate work and preventing inconsistent render state."
        ]
      }
    ],
    "tutorialLinks": []
  },
  {
    "slug": "2026-07-06",
    "title": "Standalone API Service",
    "summary": "Treease now provides a standalone API service for integrations and programmatic access.",
    "date": "2026-07-06",
    "isoDate": "2026-07-06",
    "tags": [
      "API",
      "server"
    ],
    "author": "Treease Team",
    "featured": false,
    "sections": [
      {
        "heading": "API access",
        "paragraphs": [
          "A standalone API service is now available, making Treease capabilities easier to consume independently from the web application."
        ]
      }
    ],
    "tutorialLinks": []
  },
  {
    "slug": "2026-07-05",
    "title": "More Consistent Example Loading",
    "summary": "Initial examples now follow the same complete editing and language-services flow as subsequent edits.",
    "date": "2026-07-05",
    "isoDate": "2026-07-05",
    "tags": [
      "editor",
      "reliability"
    ],
    "author": "Treease Team",
    "featured": false,
    "sections": [
      {
        "heading": "Editor behavior",
        "paragraphs": [
          "Examples loaded when the editor opens now receive the same processing as later edits, keeping highlighting, analysis, and graph output consistent."
        ]
      }
    ],
    "tutorialLinks": []
  },
  {
    "slug": "2026-07-04",
    "title": "New Editor Presets, Tutorials, and Smoother Viewer Interactions",
    "summary": "Treease adds reusable tutorial pages and URL-backed editor presets while improving graph navigation, import feedback, and CLI rendering.",
    "date": "2026-07-04",
    "isoDate": "2026-07-04",
    "tags": [
      "editor",
      "tutorials",
      "graph",
      "CLI",
      "JSON"
    ],
    "author": "Treease Team",
    "featured": false,
    "sections": [
      {
        "heading": "URL-backed editing",
        "paragraphs": [
          "Editors can now initialize from URL presets, making it easier to share and reopen structured-text examples and documents."
        ]
      },
      {
        "heading": "Viewer and graph improvements",
        "paragraphs": [
          "Graph search reveals the relevant table cells, empty containers render correctly, and full document replacement resets subgraph workspaces cleanly.",
          "Viewer panes remain mounted when switching modes, graph canvases provide a drag hint, and split-collapse transitions are animated."
        ]
      },
      {
        "heading": "Guidance and import feedback",
        "paragraphs": [
          "Treease now includes reusable tutorial pages and clearer editor call-to-action labels.",
          "Import progress communicates its final state more clearly, while CLI graph output handles missing and scalar values more gracefully. Local web testing is also supported by the CLI."
        ]
      }
    ],
    "tutorialLinks": [
      {
        "href": "/tutorial/url-parameters",
        "label": "Treease URL Parameters Tutorial"
      },
      {
        "href": "/tutorial/url-to-json-editor",
        "label": "How to Load URL Content into a JSON Editor"
      },
      {
        "href": "/tutorial/json-formatter",
        "label": "JSON Formatter Online: Format and Review JSON"
      }
    ]
  },
  {
    "slug": "2026-07-01",
    "title": "Clearer CLI Version and Asset Download Feedback",
    "summary": "The CLI now shows its version in help output and reports asset download progress.",
    "date": "2026-07-01",
    "isoDate": "2026-07-01",
    "tags": [
      "CLI",
      "usability"
    ],
    "author": "Treease Team",
    "featured": false,
    "sections": [
      {
        "heading": "CLI improvements",
        "paragraphs": [
          "CLI help now includes version information, and asset downloads provide visible progress so long-running setup is easier to understand."
        ]
      }
    ],
    "tutorialLinks": []
  },
  {
    "slug": "2026-06-30",
    "title": "More Reliable Runtime Readiness",
    "summary": "Web runtime readiness is now more stable, reducing flaky behavior during graph loading and interaction.",
    "date": "2026-06-30",
    "isoDate": "2026-06-30",
    "tags": [
      "reliability",
      "web"
    ],
    "author": "Treease Team",
    "featured": false,
    "sections": [
      {
        "heading": "Stable loading",
        "paragraphs": [
          "Runtime readiness handling has been improved so graph interactions become available more consistently after loading."
        ]
      }
    ],
    "tutorialLinks": []
  },
  {
    "slug": "2026-06-29",
    "title": "Improved Subgraph Workspaces and Graph Editing",
    "summary": "Subgraph editing is more coherent and reliable, while graph layout, edge convergence, minimap rendering, and CLI parsing receive important fixes.",
    "date": "2026-06-29",
    "isoDate": "2026-06-29",
    "tags": [
      "graph",
      "editing",
      "workspace",
      "CLI"
    ],
    "author": "Treease Team",
    "featured": false,
    "sections": [
      {
        "heading": "Subgraph workspace",
        "paragraphs": [
          "The subgraph workspace has a clearer layout and command toolbar, more reliable interactions, and improved handling of missing graph cells.",
          "Editing paths now target the correct cells, while unavailable cells are no longer presented as editable."
        ]
      },
      {
        "heading": "Graph and layout reliability",
        "paragraphs": [
          "Minimap borders render consistently, graph edges converge correctly, and graph relayout behavior is improved."
        ]
      },
      {
        "heading": "Parsing and formatting",
        "paragraphs": [
          "Nest-aware JSON formatting and CLI parsing regressions have been fixed, improving results for structured input and graph display."
        ]
      }
    ],
    "tutorialLinks": [
      {
        "href": "/tutorial/format-json-online",
        "label": "How to Format JSON Online with Treease"
      }
    ]
  },
  {
    "slug": "2026-06-24",
    "title": "More Predictable Parsing and Editor Highlighting",
    "summary": "Treease fixes parsing regressions, clarifies null input behavior in the CLI, and preserves highlighting when switching language examples.",
    "date": "2026-06-24",
    "isoDate": "2026-06-24",
    "tags": [
      "parsing",
      "editor",
      "CLI"
    ],
    "author": "Treease Team",
    "featured": false,
    "sections": [
      {
        "heading": "Input behavior",
        "paragraphs": [
          "Parsing regressions have been corrected, and the CLI now handles null input with the intended document semantics."
        ]
      },
      {
        "heading": "Editor highlighting",
        "paragraphs": [
          "Syntax highlighting is preserved when switching between language examples, making exploration more fluid."
        ]
      }
    ],
    "tutorialLinks": []
  },
  {
    "slug": "2026-06-18",
    "title": "Better Nested JSON Expansion and Blank Input Handling",
    "summary": "Nested JSON expansion is available again, blank text is processed consistently, and scalar output no longer adds an unwanted trailing newline.",
    "date": "2026-06-18",
    "isoDate": "2026-06-18",
    "tags": [
      "JSON",
      "formatting",
      "editor"
    ],
    "author": "Treease Team",
    "featured": false,
    "sections": [
      {
        "heading": "JSON editing and output",
        "paragraphs": [
          "Nested JSON structures can be expanded again for deeper inspection.",
          "Blank text now follows the normal analysis path, and scalar output is emitted without an extra trailing newline."
        ]
      }
    ],
    "tutorialLinks": [
      {
        "href": "/tutorial/json-viewer",
        "label": "JSON Viewer Online: Explore JSON as a Tree and Graph"
      },
      {
        "href": "/tutorial/json-formatter",
        "label": "JSON Formatter Online: Format and Review JSON"
      }
    ]
  },
  {
    "slug": "2026-06-16",
    "title": "NDJSON Import, Synchronized Viewing, and a More Capable CLI",
    "summary": "Treease adds JSONL/NDJSON import support, improves editor-to-graph synchronization, and delivers a more agent-friendly CLI with a web graph route.",
    "date": "2026-06-16",
    "isoDate": "2026-06-16",
    "tags": [
      "NDJSON",
      "import",
      "CLI",
      "graph"
    ],
    "author": "Treease Team",
    "featured": false,
    "sections": [
      {
        "heading": "Import and runtime reliability",
        "paragraphs": [
          "JSONL and NDJSON files can now be imported, with language detection routed through the shared processing path.",
          "Race conditions affecting full edits, graph rendering, and hover overflow have been fixed."
        ]
      },
      {
        "heading": "Editor and graph synchronization",
        "paragraphs": [
          "A sync toggle now links scrolling and reveal behavior between the editor and graph, making it easier to follow corresponding content."
        ]
      },
      {
        "heading": "CLI improvements",
        "paragraphs": [
          "The CLI now includes an agent-friendly command structure, structured errors, discovery commands, and a web graph route.",
          "Block-sequence parsing has been restored after a grammar regression."
        ]
      }
    ],
    "tutorialLinks": [
      {
        "href": "/tutorial/json-viewer",
        "label": "JSON Viewer Online: Explore JSON as a Tree and Graph"
      }
    ]
  },
  {
    "slug": "2026-06-14",
    "title": "Treease Initial Release",
    "summary": "Treease launches as a structured-text graph editor for exploring documents as synchronized text, tables, and graphs.",
    "date": "2026-06-14",
    "isoDate": "2026-06-14",
    "tags": [
      "release",
      "editor",
      "graph"
    ],
    "author": "Treease Team",
    "featured": false,
    "sections": [
      {
        "heading": "Explore structured text visually",
        "paragraphs": [
          "Treease connects structured-text editing with table and graph views, helping users inspect relationships and navigate complex documents."
        ]
      }
    ],
    "tutorialLinks": [
      {
        "href": "/tutorial/json-viewer",
        "label": "JSON Viewer Online: Explore JSON as a Tree and Graph"
      }
    ]
  }
] satisfies readonly ChangelogEntry[];
