// Generated by apps/web/scripts/generate-changelog.mjs. Do not edit by hand.
import type { ChangelogEntry } from './changelog';

export const generatedChangelog = [
  {
    "slug": "2026-07-22",
    "title": "A clearer changelog, better discoverability, and easier feedback",
    "summary": "Treease now makes product updates easier to find, improves search discoverability, and provides a convenient BugDrop dialog for reporting issues.",
    "date": "2026-07-22",
    "isoDate": "2026-07-22",
    "tags": [
      "changelog",
      "feedback",
      "seo"
    ],
    "author": "Treease Team",
    "featured": true,
    "sections": [
      {
        "heading": "What’s new",
        "paragraphs": [
          "A generated changelog page keeps product updates accessible in one place.",
          "SEO and GEO improvements help users discover Treease through search and answer engines.",
          "The new BugDrop feedback dialog makes it easier to report bugs and share product feedback."
        ]
      }
    ],
    "tutorialLinks": []
  },
  {
    "slug": "2026-07-21",
    "title": "Faster graphs and more reliable sessions",
    "summary": "Large graph scenes render more efficiently, streaming tables stay stable, and rate-limited usage requests now recover more gracefully.",
    "date": "2026-07-21",
    "isoDate": "2026-07-21",
    "tags": [
      "performance",
      "graphs",
      "reliability"
    ],
    "author": "Treease Team",
    "featured": false,
    "sections": [
      {
        "heading": "Performance",
        "paragraphs": [
          "Graph rendering is now virtualized around the visible viewport, reducing work for large documents.",
          "Unnecessary viewport edge redraws have been removed for smoother interaction."
        ]
      },
      {
        "heading": "Reliability",
        "paragraphs": [
          "Streaming table layouts remain stable as data arrives.",
          "Usage requests back off after rate limits instead of repeatedly retrying too aggressively.",
          "Server CORS handling now supports multiple configured origins."
        ]
      }
    ],
    "tutorialLinks": []
  },
  {
    "slug": "2026-07-20",
    "title": "More dependable accounts, usage limits, and streaming graphs",
    "summary": "Account identity, metering, billing webhooks, and streamed graph updates now behave more consistently across anonymous and signed-in sessions.",
    "date": "2026-07-20",
    "isoDate": "2026-07-20",
    "tags": [
      "accounts",
      "billing",
      "usage",
      "graphs"
    ],
    "author": "Treease Team",
    "featured": false,
    "sections": [
      {
        "heading": "Accounts and usage",
        "paragraphs": [
          "Usage metering is now unified between client and user accounts.",
          "Authentication flows handle anonymous sessions and standalone login more consistently."
        ]
      },
      {
        "heading": "Billing and graphs",
        "paragraphs": [
          "Subscription webhooks are idempotent, preventing duplicate billing effects.",
          "Streaming graph updates preserve the correct parent ownership during replacement."
        ]
      }
    ],
    "tutorialLinks": []
  },
  {
    "slug": "2026-07-19",
    "title": "Smoother sign-in, sharing, and editor navigation",
    "summary": "Treease improves authentication recovery, anonymous usage visibility, graph sharing restoration, and everyday editor navigation.",
    "date": "2026-07-19",
    "isoDate": "2026-07-19",
    "tags": [
      "authentication",
      "sharing",
      "editor",
      "billing"
    ],
    "author": "Treease Team",
    "featured": false,
    "sections": [
      {
        "heading": "Accounts and billing",
        "paragraphs": [
          "OAuth linking and fallback login flows now recover more reliably.",
          "Anonymous users can see account details and usage summaries while preserving their usage identity.",
          "Postpaid usage gating makes billing limits clearer."
        ]
      },
      {
        "heading": "Sharing and editing",
        "paragraphs": [
          "Shared graph links restore focus and editor selection more reliably.",
          "Graph selections now remain stable while hovering.",
          "The editor top bar includes a home logo, and workspace commands have been removed from the command panel.",
          "The recursive compact operator is now available for simplifying nested data."
        ]
      },
      {
        "heading": "Polish",
        "paragraphs": [
          "Homepage demo playback, account menu icons, semantic text colors, and branding have been refined."
        ]
      }
    ],
    "tutorialLinks": []
  },
  {
    "slug": "2026-07-18",
    "title": "Improved account navigation, checkout, and workspace actions",
    "summary": "Treease makes account management and pricing checkout more context-aware, improves AI credential routing, and clarifies desktop file actions.",
    "date": "2026-07-18",
    "isoDate": "2026-07-18",
    "tags": [
      "accounts",
      "billing",
      "workspaces",
      "ai"
    ],
    "author": "Treease Team",
    "featured": false,
    "sections": [
      {
        "heading": "Product updates",
        "paragraphs": [
          "Pricing checkout now adapts to whether a user is signed in.",
          "Account navigation is easier to follow.",
          "AI credentials are routed through the server more reliably.",
          "Desktop file actions are now grouped in the workspace menu.",
          "CLI graph output can be prerendered for faster initial display."
        ]
      }
    ],
    "tutorialLinks": []
  },
  {
    "slug": "2026-07-12",
    "title": "Faster streamed imports and desktop workspaces",
    "summary": "Streamed trace imports are faster, and the desktop experience now has a workspace host with a release-ready workflow.",
    "date": "2026-07-12",
    "isoDate": "2026-07-12",
    "tags": [
      "performance",
      "desktop",
      "workspaces"
    ],
    "author": "Treease Team",
    "featured": false,
    "sections": [
      {
        "heading": "Updates",
        "paragraphs": [
          "Streamed trace imports now complete more efficiently.",
          "Desktop users gain a workspace host for managing Treease projects."
        ]
      }
    ],
    "tutorialLinks": []
  },
  {
    "slug": "2026-07-10",
    "title": "Accounts, sharing, analytics, and pricing flows",
    "summary": "Treease adds the core account, sharing, analytics, and pricing experiences needed for a more complete hosted product.",
    "date": "2026-07-10",
    "isoDate": "2026-07-10",
    "tags": [
      "accounts",
      "sharing",
      "analytics",
      "pricing"
    ],
    "author": "Treease Team",
    "featured": false,
    "sections": [
      {
        "heading": "Product foundation",
        "paragraphs": [
          "Users can work with account-aware sharing and pricing flows, with analytics supporting the new product experience."
        ]
      }
    ],
    "tutorialLinks": []
  },
  {
    "slug": "2026-07-08",
    "title": "Clearer structured comparison diffs",
    "summary": "JSON comparisons now use explicit byte spans, making changed regions more accurate and easier to review.",
    "date": "2026-07-08",
    "isoDate": "2026-07-08",
    "tags": [
      "compare",
      "json",
      "editor"
    ],
    "author": "Treease Team",
    "featured": false,
    "sections": [
      {
        "heading": "Compare improvements",
        "paragraphs": [
          "Structured compare results now highlight the correct source ranges, improving review of additions, removals, and changes."
        ]
      }
    ],
    "tutorialLinks": [
      {
        "href": "/tutorial/compare-json-structurally",
        "label": "How to Compare JSON Structurally"
      },
      {
        "href": "/tutorial/json-compare",
        "label": "JSON Compare Online: Compare JSON Structurally"
      }
    ]
  },
  {
    "slug": "2026-07-07",
    "title": "More stable graph rendering and workspace resizing",
    "summary": "Graph readiness and workspace resizing are more dependable, with fewer timing-related rendering issues.",
    "date": "2026-07-07",
    "isoDate": "2026-07-07",
    "tags": [
      "graphs",
      "reliability",
      "layout"
    ],
    "author": "Treease Team",
    "featured": false,
    "sections": [
      {
        "heading": "Reliability improvements",
        "paragraphs": [
          "Workspace resizing now stays synchronized with the visible layout.",
          "Graph rendering readiness is more stable during initialization.",
          "Graph probing remains consistent instead of spawning competing controllers."
        ]
      }
    ],
    "tutorialLinks": []
  },
  {
    "slug": "2026-07-06",
    "title": "Standalone API service",
    "summary": "Treease now provides a standalone API service for integrations and programmatic access.",
    "date": "2026-07-06",
    "isoDate": "2026-07-06",
    "tags": [
      "api",
      "server"
    ],
    "author": "Treease Team",
    "featured": false,
    "sections": [
      {
        "heading": "New capability",
        "paragraphs": [
          "The standalone service makes Treease functionality available independently from the web editor."
        ]
      }
    ],
    "tutorialLinks": []
  },
  {
    "slug": "2026-07-05",
    "title": "More complete initial example loading",
    "summary": "The initial example now follows the same editing and language-service path as later changes, producing a more consistent first experience.",
    "date": "2026-07-05",
    "isoDate": "2026-07-05",
    "tags": [
      "editor",
      "reliability"
    ],
    "author": "Treease Team",
    "featured": false,
    "sections": [
      {
        "heading": "Editor reliability",
        "paragraphs": [
          "Opening an example now initializes parsing, editing, and language services consistently from the start."
        ]
      }
    ],
    "tutorialLinks": []
  },
  {
    "slug": "2026-07-04",
    "title": "URL presets, tutorials, and a smoother editor",
    "summary": "Treease adds reusable tutorials and URL-backed editor presets while improving graph search, import progress, pane behavior, CLI rendering, and editor motion.",
    "date": "2026-07-04",
    "isoDate": "2026-07-04",
    "tags": [
      "editor",
      "tutorials",
      "url",
      "graphs",
      "cli"
    ],
    "author": "Treease Team",
    "featured": false,
    "sections": [
      {
        "heading": "New ways to learn and load data",
        "paragraphs": [
          "Reusable tutorial pages explain common Treease workflows.",
          "URL-backed editor presets let users initialize documents from shared parameters or URL content."
        ]
      },
      {
        "heading": "Editor and graph improvements",
        "paragraphs": [
          "Graph search reveals the relevant table cells more reliably.",
          "Subgraph workspaces reset correctly after full document replacement.",
          "Empty containers render as scalar cells where appropriate.",
          "Import progress now communicates its final state clearly.",
          "Viewer panes stay mounted across mode changes.",
          "Editor calls to action and split-collapse transitions are clearer and smoother.",
          "A graph canvas drag hint helps new users discover navigation."
        ]
      },
      {
        "heading": "CLI improvements",
        "paragraphs": [
          "CLI graph rendering handles missing values and scalar data more clearly.",
          "Local web testing is now supported."
        ]
      }
    ],
    "tutorialLinks": [
      {
        "href": "/tutorial/url-parameters",
        "label": "Treease URL Parameters Tutorial"
      },
      {
        "href": "/tutorial/url-to-json-editor",
        "label": "How to Load URL Content into a JSON Editor"
      },
      {
        "href": "/tutorial/json-viewer",
        "label": "JSON Viewer Online: Explore JSON as a Tree and Graph"
      }
    ]
  },
  {
    "slug": "2026-07-01",
    "title": "Clearer CLI help and asset downloads",
    "summary": "The CLI now reports its version in help output and shows progress while downloading required assets.",
    "date": "2026-07-01",
    "isoDate": "2026-07-01",
    "tags": [
      "cli",
      "usability"
    ],
    "author": "Treease Team",
    "featured": false,
    "sections": [
      {
        "heading": "CLI updates",
        "paragraphs": [
          "Version information is available directly from help output.",
          "Asset downloads now provide visible progress feedback."
        ]
      }
    ],
    "tutorialLinks": []
  },
  {
    "slug": "2026-06-30",
    "title": "More reliable web runtime behavior",
    "summary": "Web asset checks, hover imports, runtime readiness, and end-to-end interactions are now more stable.",
    "date": "2026-06-30",
    "isoDate": "2026-06-30",
    "tags": [
      "web",
      "reliability"
    ],
    "author": "Treease Team",
    "featured": false,
    "sections": [
      {
        "heading": "Reliability improvements",
        "paragraphs": [
          "Pages validate and load web assets more consistently.",
          "Hover-based imports and runtime initialization are less prone to flaky behavior."
        ]
      }
    ],
    "tutorialLinks": []
  },
  {
    "slug": "2026-06-29",
    "title": "A more dependable subgraph workspace",
    "summary": "Subgraph editing, missing-cell handling, graph edges, and formatting now behave more predictably across complex documents.",
    "date": "2026-06-29",
    "isoDate": "2026-06-29",
    "tags": [
      "subgraphs",
      "editing",
      "graphs",
      "formatting"
    ],
    "author": "Treease Team",
    "featured": false,
    "sections": [
      {
        "heading": "Workspace improvements",
        "paragraphs": [
          "Subgraph workspace layout and interactions have been refined.",
          "Table edit paths now target the correct cells.",
          "Missing graph cells are clearly non-editable instead of accepting invalid edits.",
          "Minimap borders and editor toolbar controls have been polished."
        ]
      },
      {
        "heading": "Graph and formatting fixes",
        "paragraphs": [
          "Graph edge convergence is more stable.",
          "Nest-aware JSON formatting now preserves the intended structure."
        ]
      }
    ],
    "tutorialLinks": [
      {
        "href": "/tutorial/json-formatter",
        "label": "JSON Formatter Online: Format and Review JSON"
      }
    ]
  },
  {
    "slug": "2026-06-26",
    "title": "Improved CLI version support and graph relayout",
    "summary": "The CLI handles version information more consistently and produces improved graph layouts.",
    "date": "2026-06-26",
    "isoDate": "2026-06-26",
    "tags": [
      "cli",
      "graphs"
    ],
    "author": "Treease Team",
    "featured": false,
    "sections": [
      {
        "heading": "Updates",
        "paragraphs": [
          "CLI version support has been expanded.",
          "Graph relayout produces clearer results for rendered structures."
        ]
      }
    ],
    "tutorialLinks": []
  },
  {
    "slug": "2026-06-24",
    "title": "More consistent CLI parsing and input handling",
    "summary": "The CLI fixes parsing regressions, clarifies null input behavior, and removes the obsolete examples doctor command.",
    "date": "2026-06-24",
    "isoDate": "2026-06-24",
    "tags": [
      "cli",
      "parsing"
    ],
    "author": "Treease Team",
    "featured": false,
    "sections": [
      {
        "heading": "CLI fixes",
        "paragraphs": [
          "Parsing regressions have been corrected.",
          "Null input now follows consistent document semantics.",
          "The obsolete examples doctor command has been removed."
        ]
      }
    ],
    "tutorialLinks": []
  },
  {
    "slug": "2026-06-23",
    "title": "Preserved highlights when switching examples",
    "summary": "Changing language examples now keeps the relevant editor highlight instead of losing visual context.",
    "date": "2026-06-23",
    "isoDate": "2026-06-23",
    "tags": [
      "editor",
      "usability"
    ],
    "author": "Treease Team",
    "featured": false,
    "sections": [
      {
        "heading": "Editor polish",
        "paragraphs": [
          "Highlights now remain visible when switching between language examples."
        ]
      }
    ],
    "tutorialLinks": []
  },
  {
    "slug": "2026-06-18",
    "title": "JSONL imports, faster analysis, and improved CLI workflows",
    "summary": "Treease expands import support, improves streamed analysis and synchronization, and delivers a more capable CLI and web graph route.",
    "date": "2026-06-18",
    "isoDate": "2026-06-18",
    "tags": [
      "jsonl",
      "ndjson",
      "imports",
      "cli",
      "performance"
    ],
    "author": "Treease Team",
    "featured": false,
    "sections": [
      {
        "heading": "Import and analysis",
        "paragraphs": [
          "Nested JSON expansion is available again.",
          "JSONL and NDJSON imports are supported.",
          "Blank input is handled through the normal analysis path, and scalar output no longer adds an unwanted trailing newline.",
          "Streamed editing, graph rendering, and hover interactions are more resistant to race conditions."
        ]
      },
      {
        "heading": "CLI and web workflows",
        "paragraphs": [
          "The CLI has structured errors, discovery commands, and a web graph route.",
          "Scroll and reveal linkage can be synchronized.",
          "Parsing behavior for block sequences has been restored."
        ]
      }
    ],
    "tutorialLinks": [
      {
        "href": "/tutorial/json-viewer",
        "label": "JSON Viewer Online: Explore JSON as a Tree and Graph"
      },
      {
        "href": "/tutorial/json-formatter",
        "label": "JSON Formatter Online: Format and Review JSON"
      }
    ]
  },
  {
    "slug": "2026-06-14",
    "title": "Treease launches",
    "summary": "Treease introduces a structured-text editor that turns nested data into an interactive tree and graph.",
    "date": "2026-06-14",
    "isoDate": "2026-06-14",
    "tags": [
      "launch",
      "editor",
      "graphs"
    ],
    "author": "Treease Team",
    "featured": false,
    "sections": [
      {
        "heading": "Welcome to Treease",
        "paragraphs": [
          "Explore, edit, format, and understand structured data through synchronized text, tree, and graph views."
        ]
      }
    ],
    "tutorialLinks": [
      {
        "href": "/tutorial/json-viewer",
        "label": "JSON Viewer Online: Explore JSON as a Tree and Graph"
      }
    ]
  }
] satisfies readonly ChangelogEntry[];
