packages:
  - 'apps/web'
  - 'apps/desktop'
  - 'apps/cli'
  - 'apps/extension'
  - 'packages/*'
allowBuilds:
  '@sentry/cli': true
  edgedriver: true
  esbuild: true
  geckodriver: true
  sharp: true
  workerd: true
minimumReleaseAgeExclude:
  - '@leafer-in/editor@2.2.7'
  - '@leafer-in/export@2.2.7'
  - '@leafer-in/interface@2.2.7'
  - '@leafer-in/resize@2.2.7'
  - '@leafer-in/state@2.2.7'
  - '@leafer-in/text-editor@2.2.7'
  - '@leafer-in/view@2.2.7'
  - '@leafer-in/viewport@2.2.7'
  - '@leafer-ui/app@2.2.7'
  - '@leafer-ui/bounds@2.2.7'
  - '@leafer-ui/color@2.2.7'
  - '@leafer-ui/core@2.2.7'
  - '@leafer-ui/data@2.2.7'
  - '@leafer-ui/decorator@2.2.7'
  - '@leafer-ui/display-module@2.2.7'
  - '@leafer-ui/display@2.2.7'
  - '@leafer-ui/draw@2.2.7'
  - '@leafer-ui/effect@2.2.7'
  - '@leafer-ui/event@2.2.7'
  - '@leafer-ui/external@2.2.7'
  - '@leafer-ui/hit@2.2.7'
  - '@leafer-ui/interaction-web@2.2.7'
  - '@leafer-ui/interaction@2.2.7'
  - '@leafer-ui/interface@2.2.7'
  - '@leafer-ui/paint@2.2.7'
  - '@leafer-ui/partner@2.2.7'
  - '@leafer-ui/render@2.2.7'
  - '@leafer-ui/text@2.2.7'
  - '@leafer-ui/web@2.2.7'
  - '@leafer/canvas-web@2.2.7'
  - '@leafer/canvas@2.2.7'
  - '@leafer/core@2.2.7'
  - '@leafer/data@2.2.7'
  - '@leafer/debug@2.2.7'
  - '@leafer/decorator@2.2.7'
  - '@leafer/display-module@2.2.7'
  - '@leafer/display@2.2.7'
  - '@leafer/event@2.2.7'
  - '@leafer/file@2.2.7'
  - '@leafer/helper@2.2.7'
  - '@leafer/image-web@2.2.7'
  - '@leafer/image@2.2.7'
  - '@leafer/interface@2.2.7'
  - '@leafer/layout@2.2.7'
  - '@leafer/layouter@2.2.7'
  - '@leafer/list@2.2.7'
  - '@leafer/math@2.2.7'
  - '@leafer/partner@2.2.7'
  - '@leafer/path@2.2.7'
  - '@leafer/platform@2.2.7'
  - '@leafer/renderer@2.2.7'
  - '@leafer/selector@2.2.7'
  - '@leafer/task@2.2.7'
  - '@leafer/watcher@2.2.7'
  - '@leafer/web-core@2.2.7'
  - leafer-ui@2.2.7
  - '@leafer-in/animate@2.2.7'
  - '@leafer-in/color@2.2.7'
