import { spawn } from 'node:child_process';
import { mkdir, readFile, readdir, stat, unlink, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { watch } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { runBindgen } from './wasm-bindgen.mjs';
import { computeWasmFingerprint } from './wasm-fingerprint.mjs';

const copyOnly = process.argv.includes('--copy-only');

const here = path.dirname(fileURLToPath(import.meta.url));
const webDir = path.resolve(here, '..');
const rootDir = path.resolve(webDir, '..', '..');
const coreDir = path.resolve(rootDir, 'packages', 'core');
const rustWasmOut = path.resolve(coreDir, 'target', 'wasm32-unknown-unknown', 'release', 'treease_core.wasm');
const watchDirs = [
  path.resolve(coreDir, 'src'),
  path.resolve(coreDir, 'Cargo.toml'),
  path.resolve(coreDir, 'build.rs')
].filter((target) => existsSync(target));

let building = false;
let pending = false;
let timer = null;
let lastEventTime = 0;
let currentVersion = null;
let currentBuildInputsRevision = null;
let vite = null;
const debounceMs = 500;
const minIntervalMs = 1000;
const ignored = [/\.sw.$/, /~$/, /\.tmp$/, /\/target\//];

async function appendBuildInputRevision(target, revision) {
  const details = await stat(target);
  if (!details.isDirectory()) {
    revision.push(`${target}:${details.size}:${details.mtimeMs}`);
    return;
  }

  const entries = await readdir(target, { withFileTypes: true });
  for (const entry of entries.sort((left, right) => left.name.localeCompare(right.name))) {
    await appendBuildInputRevision(path.join(target, entry.name), revision);
  }
}

async function readBuildInputsRevision() {
  const revision = [];
  for (const target of watchDirs) {
    await appendBuildInputRevision(target, revision);
  }
  return revision.join('|');
}

async function removeGeneratedStaticWasmFiles(staticDir) {
  const generatedNames = new Set(['core-web.wasm', 'core-web-rs.wasm']);
  const generatedPatterns = [/^core\..+\.wasm$/, /^core-web\..+\.wasm$/, /^core-web-rs\..+\.wasm$/];
  const staleFiles = (await readdir(staticDir)).filter((name) => {
    if (generatedNames.has(name)) return true;
    return generatedPatterns.some((pattern) => pattern.test(name));
  });
  await Promise.all(staleFiles.map((name) => unlink(path.join(staticDir, name))));
  if (staleFiles.length) {
    process.stdout.write(`[wasm] removed ${staleFiles.length} legacy static wasm file(s)\n`);
  }
}

async function buildOnce() {
  if (!copyOnly) runBindgen({ optimize: false });
  if (!existsSync(rustWasmOut)) {
    throw new Error(`missing Rust wasm output: ${rustWasmOut}`);
  }
  await stat(rustWasmOut);

  const version = computeWasmFingerprint(rootDir);

  const staticDir = path.resolve(webDir, 'static');
  await mkdir(staticDir, { recursive: true });
  await removeGeneratedStaticWasmFiles(staticDir);

  const versionModuleHeader = '// Generated by scripts/wasm-dev.mjs. Do not edit.\n';
  const rustVersionModuleTarget = path.resolve(webDir, 'src', 'lib', 'wasm', 'rust-wasm.version.ts');
  const defaultVersionModuleTarget = path.resolve(webDir, 'src', 'lib', 'wasm', 'wasm.version.ts');
  await writeVersionModuleIfChanged(rustVersionModuleTarget, `${versionModuleHeader}export const rustWasmVersion = '${version}';\n`);
  await writeVersionModuleIfChanged(defaultVersionModuleTarget, `${versionModuleHeader}export const wasmVersion = '${version}';\n`);
  process.stdout.write(`[wasm] synced ${version}\n`);
  return version;
}

async function writeVersionModuleIfChanged(target, contents) {
  if (existsSync(target) && (await readFile(target, 'utf8')) === contents) return;
  await writeFile(target, contents, 'utf8');
}

function startVite(version) {
  return spawn('pnpm', ['dev:vite'], {
    cwd: webDir,
    stdio: 'inherit',
    env: { ...process.env, WASM_VERSION: version, TREEASE_WASM_IMPL: 'rust' }
  });
}

function restartVite(version) {
  if (vite) {
    vite.kill('SIGTERM');
  }
  vite = startVite(version);
}

async function buildQueued() {
  if (building) {
    pending = true;
    return currentVersion;
  }
  const buildInputsRevision = await readBuildInputsRevision();
  if (buildInputsRevision === currentBuildInputsRevision) {
    return currentVersion;
  }
  building = true;
  try {
    const version = await buildOnce();
    currentBuildInputsRevision = buildInputsRevision;
    if (version && version !== currentVersion) {
      currentVersion = version;
      if (vite) {
        restartVite(currentVersion);
      }
    }
  } catch (err) {
    process.stderr.write(`[wasm] build failed: ${err.message}\n`);
  } finally {
    building = false;
    if (pending) {
      pending = false;
      await buildQueued();
    }
  }
  return currentVersion;
}

function shouldIgnore(filename) {
  if (!filename) return false;
  return ignored.some((rule) => rule.test(filename));
}

function scheduleBuild(filename) {
  if (shouldIgnore(filename)) return;
  const now = Date.now();
  if (now - lastEventTime < minIntervalMs) {
    if (timer) clearTimeout(timer);
    timer = setTimeout(() => buildQueued(), debounceMs);
    return;
  }
  lastEventTime = now;
  if (timer) clearTimeout(timer);
  timer = setTimeout(() => buildQueued(), debounceMs);
}

function startWatch() {
  for (const target of watchDirs) {
    watch(target, { recursive: true }, (_event, filename) => scheduleBuild(filename));
  }
}

async function main() {
  currentVersion = await buildQueued();
  if (copyOnly) return;
  startWatch();
  if (currentVersion) {
    vite = startVite(currentVersion);
  }
  const shutdown = () => {
    if (vite) {
      vite.kill('SIGTERM');
    }
    process.exit(0);
  };
  process.on('SIGINT', shutdown);
  process.on('SIGTERM', shutdown);
}

main().catch((err) => {
  process.stderr.write(`[wasm] fatal: ${err.message}\n`);
  process.exit(1);
});
