import { spawn } from 'node:child_process';
import { mkdir, readFile, readdir, stat, unlink, writeFile } from 'node:fs/promises';
import { existsSync, readFileSync } from 'node:fs';
import { watch } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createHash } from 'node:crypto';
import { runBindgen } from './wasm-bindgen.mjs';
import { optimizeWasmSync } from './wasm-optimize.mjs';

const copyOnly = process.argv.includes('--copy-only');

const here = path.dirname(fileURLToPath(import.meta.url));
const webDir = path.resolve(here, '..');
const rootDir = path.resolve(webDir, '..', '..');
const coreDir = path.resolve(rootDir, 'packages', 'core');
const coreManifest = path.resolve(coreDir, 'Cargo.toml');
const versionFile = path.resolve(coreDir, 'output', 'core-web.version');
const rustWasmOut = path.resolve(coreDir, 'target', 'wasm32-unknown-unknown', 'release', 'treease_core.wasm');
const rustWasmOptimizedOut = path.resolve(
  coreDir,
  'target',
  'wasm32-unknown-unknown',
  'release',
  'treease_core.opt.wasm'
);
const watchDirs = [
  path.resolve(coreDir, 'src'),
  path.resolve(coreDir, 'tests'),
  path.resolve(coreDir, 'Cargo.toml'),
  path.resolve(coreDir, 'build.rs')
].filter((target) => existsSync(target));

let building = false;
let pending = false;
let timer = null;
let lastEventTime = 0;
let currentVersion = null;
let vite = null;
const debounceMs = 500;
const minIntervalMs = 1000;
const ignored = [/\.sw.$/, /~$/, /\.tmp$/, /\/target\//];

function readManifestReleaseDate() {
  if (!existsSync(coreManifest)) return null;
  const manifest = readFileSync(coreManifest, 'utf8');
  const match = manifest.match(/^\s*wasm_release_date\s*=\s*"([0-9]{8})"\s*$/m);
  return match?.[1] ?? null;
}

async function readVersion(wasmPath) {
  const manifestReleaseDate = readManifestReleaseDate();
  if (manifestReleaseDate) {
    return manifestReleaseDate;
  }
  if (existsSync(versionFile)) {
    const version = (await readFile(versionFile, 'utf8')).trim();
    if (version) return version;
  }
  const bytes = await readFile(wasmPath);
  return createHash('sha256').update(bytes).digest('hex').slice(0, 6);
}

async function optimizeWasm() {
  optimizeWasmSync(rustWasmOut, rustWasmOptimizedOut);
  return rustWasmOptimizedOut;
}

async function removeGeneratedStaticWasmFiles(staticDir) {
  const generatedNames = new Set(['core-web.wasm', 'core-web-rs.wasm']);
  const generatedPatterns = [/^core\..+\.wasm$/, /^core-web\..+\.wasm$/, /^core-web-rs\..+\.wasm$/];
  const staleFiles = (await readdir(staticDir)).filter((name) => {
    if (generatedNames.has(name)) return true;
    return generatedPatterns.some((pattern) => pattern.test(name));
  });
  await Promise.all(staleFiles.map((name) => unlink(path.join(staticDir, name))));
  if (staleFiles.length) {
    process.stdout.write(`[wasm] removed ${staleFiles.length} legacy static wasm file(s)\n`);
  }
}

async function buildOnce() {
  if (!copyOnly) runBindgen();
  if (!existsSync(rustWasmOut)) {
    throw new Error(`missing Rust wasm output: ${rustWasmOut}`);
  }
  await stat(rustWasmOut);

  const wasmSource = await optimizeWasm();
  const version = await readVersion(wasmSource);

  const staticDir = path.resolve(webDir, 'static');
  await mkdir(staticDir, { recursive: true });
  await removeGeneratedStaticWasmFiles(staticDir);

  const versionModuleHeader = '// Generated by scripts/wasm-dev.mjs. Do not edit.\n';
  const rustVersionModuleTarget = path.resolve(webDir, 'src', 'lib', 'wasm', 'rust-wasm.version.ts');
  const defaultVersionModuleTarget = path.resolve(webDir, 'src', 'lib', 'wasm', 'wasm.version.ts');
  await writeFile(rustVersionModuleTarget, `${versionModuleHeader}export const rustWasmVersion = '${version}';\n`, 'utf8');
  await writeFile(defaultVersionModuleTarget, `${versionModuleHeader}export const wasmVersion = '${version}';\n`, 'utf8');
  process.stdout.write(`[wasm] synced ${version}\n`);
  return version;
}

function startVite(version) {
  return spawn('pnpm', ['dev:vite'], {
    cwd: webDir,
    stdio: 'inherit',
    env: { ...process.env, VITE_WASM_VERSION: version, VITE_TREEASE_WASM_IMPL: 'rust' }
  });
}

function restartVite(version) {
  if (vite) {
    vite.kill('SIGTERM');
  }
  vite = startVite(version);
}

async function buildQueued() {
  if (building) {
    pending = true;
    return currentVersion;
  }
  building = true;
  try {
    const version = await buildOnce();
    if (version && version !== currentVersion) {
      currentVersion = version;
      if (vite) {
        restartVite(currentVersion);
      }
    }
  } catch (err) {
    process.stderr.write(`[wasm] build failed: ${err.message}\n`);
  } finally {
    building = false;
    if (pending) {
      pending = false;
      await buildQueued();
    }
  }
  return currentVersion;
}

function shouldIgnore(filename) {
  if (!filename) return false;
  return ignored.some((rule) => rule.test(filename));
}

function scheduleBuild(filename) {
  if (shouldIgnore(filename)) return;
  const now = Date.now();
  if (now - lastEventTime < minIntervalMs) {
    if (timer) clearTimeout(timer);
    timer = setTimeout(() => buildQueued(), debounceMs);
    return;
  }
  lastEventTime = now;
  if (timer) clearTimeout(timer);
  timer = setTimeout(() => buildQueued(), debounceMs);
}

function startWatch() {
  for (const target of watchDirs) {
    watch(target, { recursive: true }, (_event, filename) => scheduleBuild(filename));
  }
}

async function main() {
  currentVersion = await buildQueued();
  if (copyOnly) return;
  startWatch();
  if (currentVersion) {
    vite = startVite(currentVersion);
  }
  const shutdown = () => {
    if (vite) {
      vite.kill('SIGTERM');
    }
    process.exit(0);
  };
  process.on('SIGINT', shutdown);
  process.on('SIGTERM', shutdown);
}

main().catch((err) => {
  process.stderr.write(`[wasm] fatal: ${err.message}\n`);
  process.exit(1);
});
