// Generated by `cargo run --locked --bin export_document_protocol`. Do not edit.

export type SnapshotId = number;

export type CommitMode = "authoritative" | "diagnosticsOnly";

export type DocumentJobKind = "analyzeSource" | "applyEdits";

export type DocumentInputPlan = "sourceText" | "baseTextWithEdits" | "byteStream";

export interface DocumentParserSettings {
    enableNest: boolean;
    nestMaxDepth: number;
}

export interface DocumentFormattingSettings {
    indent: number;
    smart: boolean;
    formatSourceOnClose: boolean;
    maxLineLength: number;
    maxInlineComplexity: number;
    maxArrayInlineItems: number;
    alignObjectArrays: boolean;
}

export interface DocumentJobSettings {
    parser: DocumentParserSettings;
    formatting: DocumentFormattingSettings;
}

export interface OutputPlan {
    analysis: boolean;
    graph: boolean;
}

export interface ProjectionRequest {
    snapshotId: SnapshotId;
    path: string;
}

export interface GraphPathSeg {
    tag: number;
    key: string;
    index: number;
}

export type GraphValueEditPlanMode = "edits" | "replace";

export type GraphValueEditFallbackReason = "unsupportedEdit" | "snapshotNotReady" | "missingAnalysis" | "missingDocument" | "invalidPath" | "invalidReplacement" | "unsupportedLanguage" | "unsafeEdit";

export interface DocumentTextEdit {
    startByte: number;
    oldEndByte: number;
    newEndByte: number;
    text: string;
}

export interface GraphValueEditRequest {
    documentKey: string;
    snapshotId: SnapshotId;
    language: string;
    path: GraphPathSeg[];
    preferKey: boolean;
    value: any;
    rawReplacement?: string | null;
}

export interface GraphValueEditPlan {
    mode: GraphValueEditPlanMode;
    edits: DocumentTextEdit[];
    reason: GraphValueEditFallbackReason | null;
}

export interface GraphBoxArgs {
    x: number;
    y: number;
    width: number;
    height: number;
    cornerRadius: number;
}

export interface GraphTextArgs {
    x: number;
    y: number;
    width: number;
    height: number;
    text: string;
    textAlign: number;
    textVerticalAlign: number;
    editable: boolean;
}

export interface GraphCellData {
    semType: number;
    isMissing: boolean;
    path: GraphPathSeg[];
    text: string;
    value: string;
    formatText: string;
    boxArgs: GraphBoxArgs;
    textArgs: GraphTextArgs;
}

export interface GraphRowData {
    index: number;
    boxArgs: GraphBoxArgs;
    cellBoxArgs: GraphBoxArgs;
    cells: GraphCellData[];
}

export interface GraphTableData {
    columns: GraphCellData[];
    rows: GraphRowData[];
    headerHeight: number;
    totalHeight: number;
    viewHeight: number;
    rowHeight: number;
}

export interface GraphNodeData {
    renderHandle: number;
    kind: number;
    path: GraphPathSeg[];
    depth: number;
    boxArgs: GraphBoxArgs;
    meta: GraphCellData | null;
    rows: GraphRowData[];
    table: GraphTableData | null;
}

export interface GraphBezierArgsData {
    fromX: number;
    fromY: number;
    c1x: number;
    c1y: number;
    c2x: number;
    c2y: number;
    toX: number;
    toY: number;
}

export interface GraphEdgeData {
    fromRenderHandle: number;
    fromKind: number;
    fromPath: GraphPathSeg[];
    fromRow: number;
    toRenderHandle: number;
    toKind: number;
    toPath: GraphPathSeg[];
    toRow: number;
    bezierArgs: GraphBezierArgsData;
    bezierFromX: number;
    bezierFromY: number;
    bezierC1x: number;
    bezierC1y: number;
    bezierC2x: number;
    bezierC2y: number;
    bezierToX: number;
    bezierToY: number;
}

export interface GraphEdgeRemoved {
    from: number;
    to: number;
}

export interface GraphDelta {
    nodesAdded: GraphNodeData[];
    nodesUpdated: GraphNodeData[];
    nodesRemoved: number[];
    edgesAdded: GraphEdgeData[];
    edgesRemoved: GraphEdgeRemoved[];
    tablePatches?: TablePatch[];
    layoutPatches?: LayoutPatch[];
}

export type TablePatch = { kind: "tableCreated"; table_handle: number; columns: GraphCellData[] } | { kind: "rowsAppended"; table_handle: number; start_index: number; rows: GraphRowData[]; total_height: number; view_height: number; header_height: number; row_height: number } | { kind: "cellsUpdated"; table_handle: number; cells: TableCellPatchData[] } | { kind: "columnsAdded"; table_handle: number; columns: GraphCellData[] } | { kind: "tableReplaced"; table_handle: number; table: GraphTableData };

export type LayoutPatch = { kind: "nodeBoundsUpdated"; render_handle: number; box_args: GraphBoxArgs } | { kind: "groupLayoutUpdated"; group_handle: number; width: number; height: number } | { kind: "viewportLayoutHint"; total_height: number; appended_height: number };

export interface TableCellPatchData {
    rowIndex: number;
    columnIndex: number;
    cell: GraphCellData;
}

export interface DocumentDiagnostic {
    startLineNumber: number;
    startColumn: number;
    endLineNumber: number;
    endColumn: number;
    kind: number;
}

export interface SemanticTokensPayload {
    data: number[];
    version: number;
}

export interface DocumentTreeNode {
    kind: number;
    semType: number;
    tag: string;
    value: string;
    children: DocumentTreeNode[];
}

export interface DocumentNodePreview {
    kind: number;
    semType: number;
    tag: string;
    value: string;
    valueType?: string;
    isScalar?: boolean;
}

export interface DocumentPathValue {
    valueType: string;
    value: string;
    sourceText: string;
    displayText: string;
    semanticTokens: SemanticTokensPayload;
}

export type DocumentDirectChild = { kind: "key"; key: string; preview: string; valueType: string; semType: number; isContainer: boolean } | { kind: "index"; index: number; preview: string; valueType: string; semType: number; isContainer: boolean };

export interface DocumentSearchItem {
    path: string;
    pathText: string;
    label: string;
    keyText: string;
    valueText: string;
    target: QueryTargetKind;
}

export interface DocumentAnalysisPayload {
    tree: DocumentTreeNode | null;
    valueJson?: string | null;
    diagnostics: DocumentDiagnostic[];
    semanticTokens: SemanticTokensPayload;
    sourceByteLength: number;
    sourceLineCount?: number;
    language: string;
}

export interface ProjectionDelta {
    clear: boolean;
    graphData: GraphDelta | null;
    patchSeq?: number;
    baseGraphVersion?: number;
    graphVersion?: number;
}

export interface SnapshotReady {
    snapshotId: SnapshotId;
    analysis: DocumentAnalysisPayload | null;
    mainGraph: ProjectionDelta | null;
    sourceText?: string | null;
}

export interface ParseFailed {
    snapshotId: SnapshotId;
    analysis: DocumentAnalysisPayload;
}

export interface DocumentJobSpec {
    kind: DocumentJobKind;
    documentKey: string;
    language: string;
    input: DocumentInputPlan;
    settings?: DocumentJobSettings;
    output: OutputPlan;
    baseSnapshotId: SnapshotId | null;
    edits: any[];
}

export type AdvanceInput = "poll" | { textChunk: string } | { binaryChunk: number[] } | "close";

export type DocumentEvent = { type: "progress"; processedBytes: number } | { type: "analysisDelta"; analysis: DocumentAnalysisPayload } | { type: "snapshotReady"; snapshotId: SnapshotId; analysis: DocumentAnalysisPayload | null; mainGraph: ProjectionDelta | null; sourceText?: string | null } | { type: "parseFailed"; snapshotId: SnapshotId; analysis: DocumentAnalysisPayload } | { type: "projectionDelta"; clear: boolean; graphData: GraphDelta | null; patchSeq?: number; baseGraphVersion?: number; graphVersion?: number };

export type JobTerminal = { type: "completed" } | { type: "parseFailed" } | { type: "rejected"; code: string; detail: string } | { type: "cancelled" };

export interface EventBatch {
    requestSeq: number;
    events: DocumentEvent[];
    terminal: JobTerminal | null;
}

export interface DocumentAnchor {
    snapshotId: SnapshotId;
    path: string;
    spanStart: number;
    spanEnd: number;
}

export type QueryKind = "findAnchors" | "resolvePath" | "resolveHover" | "rootValueKind" | "nodePreview" | "pathValue" | "fieldLabels" | "searchIndex" | "directChildren";

export type QueryTargetKind = "key" | "value" | "node";

export interface SnapshotQuery {
    snapshotId: SnapshotId;
    kind: QueryKind;
    pathPattern: string | null;
    span: [number, number] | null;
    target: QueryTargetKind | null;
}

export interface QueryResult {
    anchors: DocumentAnchor[];
    rootValueKind?: string | null;
    nodePreview?: DocumentNodePreview | null;
    pathValue?: DocumentPathValue | null;
    directChildren?: DocumentDirectChild[];
    fieldLabels?: string[];
    searchItems?: DocumentSearchItem[];
}

export type SnapshotReadResult<T> = { status: "ready"; data: T } | { status: "snapshotNotReady" };

