// Generated by `cargo run --locked --bin export_language_support`. Do not edit.

export const supportedEditorLanguages = [
  { id: 'json', label: 'JSON', extensions: ['.json'], exampleExtensions: ['json'] },
  { id: 'yaml', label: 'YAML', extensions: ['.yaml', '.yml'], exampleExtensions: ['yaml', 'yml'] },
  { id: 'toml', label: 'TOML', extensions: ['.toml'], exampleExtensions: ['toml'] },
  { id: 'python', label: 'Python Dict', extensions: ['.py'], exampleExtensions: ['py'] },
  { id: 'javascript', label: 'JS Object', extensions: ['.js', '.mjs', '.cjs'], exampleExtensions: ['js'] },
] as const;

export type SupportedEditorLanguageId = (typeof supportedEditorLanguages)[number]['id'];

export const supportedEditorLanguageIds = supportedEditorLanguages.map((item) => item.id) as SupportedEditorLanguageId[];
export const supportedEditorLanguageSet = new Set<SupportedEditorLanguageId>(supportedEditorLanguageIds);
export const editorLanguageFallback = supportedEditorLanguageIds[0];

export const importOnlyLanguages = [
  { id: 'csv', label: 'CSV', extensions: ['.csv'] },
] as const;

export type ImportOnlyLanguageId = (typeof importOnlyLanguages)[number]['id'];

export type SupportedLanguageId = SupportedEditorLanguageId | ImportOnlyLanguageId;

type SupportedLanguageOption = (typeof supportedEditorLanguages)[number] | (typeof importOnlyLanguages)[number];

const supportedLanguageOptions: ReadonlyArray<SupportedLanguageOption> = [
  ...supportedEditorLanguages,
  ...importOnlyLanguages,
];

export const importFormatOptions: Array<{
  id: SupportedLanguageId
  label: string
  extensions: string[]
}> = [
  { id: 'json' as SupportedLanguageId, label: 'JSON', extensions: ['.json'] },
  { id: 'yaml' as SupportedLanguageId, label: 'YAML', extensions: ['.yaml', '.yml'] },
  { id: 'toml' as SupportedLanguageId, label: 'TOML', extensions: ['.toml'] },
  { id: 'csv' as SupportedLanguageId, label: 'CSV', extensions: ['.csv'] },
];

export function findSupportedLanguageByExtension(extension: string): SupportedLanguageId | null {
  const normalized = extension.toLowerCase();
  const option = supportedLanguageOptions.find((item) => item.extensions.some((itemExtension) => itemExtension === normalized));
  return option?.id ?? null;
}

const editorExampleExtensions = supportedEditorLanguages.flatMap((item) =>
  item.exampleExtensions.map((extension) => [extension.toLowerCase(), item.id] as const),
);

export const exampleLanguageByExtension = new Map<string, SupportedEditorLanguageId>(editorExampleExtensions);

export function findExampleLanguageByExtension(extension: string): SupportedEditorLanguageId | null {
  return exampleLanguageByExtension.get(extension.toLowerCase()) ?? null;
}
