use std::collections::BTreeSet;
use std::fs;
use std::path::{Path, PathBuf};

use treease_core::core::DocumentTextEdit;
use treease_core::document::{
    AdvanceInput, CommitMode, DocumentAnalysisPayload, DocumentAnchor, DocumentDiagnostic,
    DocumentEvent, DocumentFormattingSettings, DocumentInputPlan, DocumentJobKind,
    DocumentJobSettings, DocumentJobSpec, DocumentParserSettings, DocumentTreeNode, EventBatch,
    GraphBezierArgsData, GraphBoxArgs, GraphCellData, GraphDelta, GraphEdgeData, GraphEdgeRemoved,
    GraphNodeData, GraphPathSeg, GraphRowData, GraphTableData, GraphTextArgs,
    GraphValueEditFallbackReason, GraphValueEditPlan, GraphValueEditPlanMode,
    GraphValueEditRequest, JobTerminal, LayoutPatch, OutputPlan, ParseFailed, ProjectionDelta,
    ProjectionRequest, QueryKind, QueryResult, QueryTargetKind, SemanticTokensPayload, SnapshotId,
    SnapshotQuery, SnapshotReadResult, SnapshotReady, TableCellPatchData, TablePatch,
};
use tsify::Tsify;

fn package_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).to_path_buf()
}

fn declaration_list() -> Vec<&'static str> {
    vec![
        <SnapshotId as Tsify>::DECL,
        <CommitMode as Tsify>::DECL,
        <DocumentJobKind as Tsify>::DECL,
        <DocumentInputPlan as Tsify>::DECL,
        <DocumentParserSettings as Tsify>::DECL,
        <DocumentFormattingSettings as Tsify>::DECL,
        <DocumentJobSettings as Tsify>::DECL,
        <OutputPlan as Tsify>::DECL,
        <ProjectionRequest as Tsify>::DECL,
        <GraphPathSeg as Tsify>::DECL,
        <GraphValueEditPlanMode as Tsify>::DECL,
        <GraphValueEditFallbackReason as Tsify>::DECL,
        <DocumentTextEdit as Tsify>::DECL,
        <GraphValueEditRequest as Tsify>::DECL,
        <GraphValueEditPlan as Tsify>::DECL,
        <GraphBoxArgs as Tsify>::DECL,
        <GraphTextArgs as Tsify>::DECL,
        <GraphCellData as Tsify>::DECL,
        <GraphRowData as Tsify>::DECL,
        <GraphTableData as Tsify>::DECL,
        <GraphNodeData as Tsify>::DECL,
        <GraphBezierArgsData as Tsify>::DECL,
        <GraphEdgeData as Tsify>::DECL,
        <GraphEdgeRemoved as Tsify>::DECL,
        <GraphDelta as Tsify>::DECL,
        <TablePatch as Tsify>::DECL,
        <LayoutPatch as Tsify>::DECL,
        <TableCellPatchData as Tsify>::DECL,
        <DocumentDiagnostic as Tsify>::DECL,
        <SemanticTokensPayload as Tsify>::DECL,
        <DocumentTreeNode as Tsify>::DECL,
        <DocumentAnalysisPayload as Tsify>::DECL,
        <ProjectionDelta as Tsify>::DECL,
        <SnapshotReady as Tsify>::DECL,
        <ParseFailed as Tsify>::DECL,
        <DocumentJobSpec as Tsify>::DECL,
        <AdvanceInput as Tsify>::DECL,
        <DocumentEvent as Tsify>::DECL,
        <JobTerminal as Tsify>::DECL,
        <EventBatch as Tsify>::DECL,
        <DocumentAnchor as Tsify>::DECL,
        <QueryKind as Tsify>::DECL,
        <QueryTargetKind as Tsify>::DECL,
        <SnapshotQuery as Tsify>::DECL,
    ]
}

fn build_output() -> String {
    let mut out = String::from(
        "// Generated by `cargo run --locked --bin export_document_protocol`. Do not edit.\n\n",
    );
    let mut seen = BTreeSet::new();

    for decl in declaration_list().into_iter().chain([
        <QueryResult as Tsify>::DECL,
        <GraphValueEditPlan as Tsify>::DECL,
        <SnapshotReadResult<QueryResult> as Tsify>::DECL,
        <SnapshotReadResult<GraphValueEditPlan> as Tsify>::DECL,
    ]) {
        let trimmed = decl.trim();
        if trimmed.is_empty() || !seen.insert(trimmed.to_owned()) {
            continue;
        }
        out.push_str(trimmed);
        out.push('\n');
        out.push('\n');
    }

    out
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    fs::write(
        package_root()
            .join("wasm")
            .join("document-protocol.generated.ts"),
        build_output(),
    )?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use std::collections::BTreeSet;

    use super::build_output;

    fn declared_types(output: &str) -> BTreeSet<&str> {
        output
            .lines()
            .filter_map(|line| {
                let line = line.trim();
                let rest = line
                    .strip_prefix("export interface ")
                    .or_else(|| line.strip_prefix("export type "))?;
                rest.split(|ch: char| ch == '<' || ch == ' ' || ch == '{' || ch == '=')
                    .next()
            })
            .collect()
    }

    #[test]
    fn renders_document_protocol_header() {
        let output = build_output();
        assert!(output.starts_with(
            "// Generated by `cargo run --locked --bin export_document_protocol`. Do not edit.\n\n"
        ));
        assert!(output.contains("DocumentJobSpec"));
        assert!(output.contains("ProjectionDelta"));
        assert!(output.contains("QueryResult"));
    }

    #[test]
    fn renders_graph_projection_dependencies() {
        let output = build_output();

        for expected in [
            "GraphPathSeg",
            "GraphBoxArgs",
            "GraphTextArgs",
            "GraphCellData",
            "GraphRowData",
            "GraphTableData",
            "GraphNodeData",
            "GraphEdgeData",
            "GraphEdgeRemoved",
        ] {
            assert!(
                output.contains(&format!("export interface {expected}")),
                "missing declaration for {expected}",
            );
        }
    }

    #[test]
    fn renders_no_undeclared_type_references() {
        let output = build_output();
        let declared = declared_types(&output);

        for line in output
            .lines()
            .filter(|line| !line.trim_start().starts_with("//"))
        {
            for token in line.split(|ch: char| !(ch.is_ascii_alphanumeric() || ch == '_')) {
                if !token
                    .as_bytes()
                    .first()
                    .is_some_and(|first| first.is_ascii_uppercase())
                {
                    continue;
                }
                if token == "T" {
                    continue;
                }
                assert!(
                    declared.contains(token),
                    "undeclared type reference {token} in line {line}",
                );
            }
        }
    }
}
