use std::fs;
use std::path::{Path, PathBuf};

use treease_core::core::{LANG_SPECS, LangSpec};

fn push_ts_string_array(out: &mut String, values: &[&str], prefix_dot: bool) {
    out.push('[');
    for (index, value) in values.iter().enumerate() {
        if index != 0 {
            out.push_str(", ");
        }
        out.push('\'');
        if prefix_dot {
            out.push('.');
        }
        out.push_str(value);
        out.push('\'');
    }
    out.push(']');
}

fn effective_import_extensions(spec: &'static LangSpec<'static>) -> &'static [&'static str] {
    if spec.web_import_extensions.is_empty() {
        spec.extensions
    } else {
        spec.web_import_extensions
    }
}

fn append_editor_languages(out: &mut String) {
    out.push_str("export const supportedEditorLanguages = [\n");
    for spec in LANG_SPECS {
        if !spec.enabled || !spec.web_editor_supported {
            continue;
        }
        let Some(label) = spec.web_label else {
            continue;
        };
        out.push_str("  { id: '");
        out.push_str(spec.name);
        out.push_str("', label: '");
        out.push_str(label);
        out.push_str("', extensions: ");
        push_ts_string_array(out, effective_import_extensions(spec), true);
        out.push_str(", exampleExtensions: ");
        push_ts_string_array(out, spec.web_example_extensions, false);
        out.push_str(" },\n");
    }
    out.push_str("] as const;\n\n");
}

fn append_import_only_languages(out: &mut String) {
    out.push_str("export const importOnlyLanguages = [\n");
    for spec in LANG_SPECS {
        if !spec.enabled || spec.web_editor_supported || !spec.web_import_supported {
            continue;
        }
        let Some(label) = spec.web_label else {
            continue;
        };
        out.push_str("  { id: '");
        out.push_str(spec.name);
        out.push_str("', label: '");
        out.push_str(label);
        out.push_str("', extensions: ");
        push_ts_string_array(out, effective_import_extensions(spec), true);
        out.push_str(" },\n");
    }
    out.push_str("] as const;\n\n");
}

fn append_import_format_options(out: &mut String) {
    out.push_str("export const importFormatOptions: Array<{\n");
    out.push_str("  id: SupportedLanguageId\n");
    out.push_str("  label: string\n");
    out.push_str("  extensions: string[]\n");
    out.push_str("}> = [\n");
    for spec in LANG_SPECS {
        if !spec.enabled || !spec.web_import_supported {
            continue;
        }
        let Some(label) = spec.web_label else {
            continue;
        };
        out.push_str("  { id: '");
        out.push_str(spec.name);
        out.push_str("' as SupportedLanguageId, label: '");
        out.push_str(label);
        out.push_str("', extensions: ");
        push_ts_string_array(out, effective_import_extensions(spec), true);
        out.push_str(" },\n");
    }
    out.push_str("];\n\n");
}

fn build_output() -> String {
    let mut out = String::new();
    out.push_str(
        "// Generated by `cargo run --locked --bin export_language_support`. Do not edit.\n\n",
    );
    append_editor_languages(&mut out);
    out.push_str("export type SupportedEditorLanguageId = (typeof supportedEditorLanguages)[number]['id'];\n\n");
    out.push_str("export const supportedEditorLanguageIds = supportedEditorLanguages.map((item) => item.id) as SupportedEditorLanguageId[];\n");
    out.push_str("export const supportedEditorLanguageSet = new Set<SupportedEditorLanguageId>(supportedEditorLanguageIds);\n");
    out.push_str("export const editorLanguageFallback = supportedEditorLanguageIds[0];\n\n");
    append_import_only_languages(&mut out);
    out.push_str(
        "export type ImportOnlyLanguageId = (typeof importOnlyLanguages)[number]['id'];\n\n",
    );
    out.push_str(
        "export type SupportedLanguageId = SupportedEditorLanguageId | ImportOnlyLanguageId;\n\n",
    );
    out.push_str("type SupportedLanguageOption = (typeof supportedEditorLanguages)[number] | (typeof importOnlyLanguages)[number];\n\n");
    out.push_str("const supportedLanguageOptions: ReadonlyArray<SupportedLanguageOption> = [\n");
    out.push_str("  ...supportedEditorLanguages,\n");
    out.push_str("  ...importOnlyLanguages,\n");
    out.push_str("];\n\n");
    append_import_format_options(&mut out);
    out.push_str("export function findSupportedLanguageByExtension(extension: string): SupportedLanguageId | null {\n");
    out.push_str("  const normalized = extension.toLowerCase();\n");
    out.push_str("  const option = supportedLanguageOptions.find((item) => item.extensions.some((itemExtension) => itemExtension === normalized));\n");
    out.push_str("  return option?.id ?? null;\n");
    out.push_str("}\n\n");
    out.push_str("const editorExampleExtensions = supportedEditorLanguages.flatMap((item) =>\n");
    out.push_str("  item.exampleExtensions.map((extension) => [extension.toLowerCase(), item.id] as const),\n");
    out.push_str(");\n\n");
    out.push_str("export const exampleLanguageByExtension = new Map<string, SupportedEditorLanguageId>(editorExampleExtensions);\n\n");
    out.push_str("export function findExampleLanguageByExtension(extension: string): SupportedEditorLanguageId | null {\n");
    out.push_str("  return exampleLanguageByExtension.get(extension.toLowerCase()) ?? null;\n");
    out.push_str("}\n");
    out
}

fn package_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).to_path_buf()
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let output = build_output();
    fs::write(
        package_root()
            .join("wasm")
            .join("language-support.generated.ts"),
        output,
    )?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::build_output;

    #[test]
    fn renders_language_support_with_rust_header() {
        let output = build_output();
        assert!(output.starts_with(
            "// Generated by `cargo run --locked --bin export_language_support`. Do not edit.\n\n"
        ));
        assert!(output.contains(
            "{ id: 'json', label: 'JSON', extensions: ['.json'], exampleExtensions: ['json'] }"
        ));
        assert!(output.contains("export const importOnlyLanguages = [\n  { id: 'csv', label: 'CSV', extensions: ['.csv'] },\n] as const;\n"));
    }
}
