name: Core Tests

on:
  workflow_call:

jobs:
  core-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive
      - uses: ./.github/actions/setup-rust
      - uses: taiki-e/install-action@v2
        with:
          tool: nextest
      - name: Run core tests
        run: ./test.sh all
        working-directory: ${{ github.workspace }}/packages/core
